In [20]:
#Flag Dataset
#load data
import numpy as np
import pandas as pd
import sklearn


flags = pd.read_csv('flag.data')
print(np.array(flags).transpose())

[['Albania' 'Algeria' 'American-Samoa' ... 'Zaire' 'Zambia' 'Zimbabwe']
 [3 4 6 ... 4 4 4]
 [1 1 3 ... 2 2 2]
 ...
 [0 0 0 ... 0 0 0]
 ['red' 'green' 'blue' ... 'green' 'green' 'green']
 ['red' 'white' 'red' ... 'green' 'brown' 'green']]


In [ ]:
#30 dimensions - Do PCA
